[package]
name = "trait_test"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
dyn-clone = "1.0.20"
itertools = "0.14.0"
nalgebra = "0.34.1"
rand = "0.9.2"
rayon = "1.11.0"
indicatif = { version = "0.17", features = ["rayon"] }
